spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/task-db?createDatabaseIfNotExist=true
    username: root
    password: mauFJcuf5dhRMQrjj
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
      #ddl-auto: update
    show-sql: true
