spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/tasks-db?createDatabaseIfNotExist=true
    username: root
    password: admin #mauFJcuf5dhRMQrjj
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      #ddl-auto: create-drop
      ddl-auto: create
      #ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
